apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloworld
    version: "1.0"
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: microservice-linkerd-helloworld:1
        imagePullPolicy: Never        
        ports:
        - containerPort: 80
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloworld
  name: helloworld
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http    
  selector:
    app: helloworld
  type: NodePort
status:
  loadBalancer: {}

---

#apiVersion: extensions/v1beta1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    ingress.kubernetes.io/custom-request-headers: l5d-dst-override:helloworld.default.svc.cluster.local:80
spec:
  rules:
  - http:
      paths:
      - path: /helloworld
        pathType: Exact
        backend:
          service:
            name: helloworld
            port: 
              number: 80

