apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: nameapi-split
  namespace: default
spec:
  service: nameapi
  backends:
  - service: nameapi
    weight: 0
  - service: nameapi-v2
    weight: 100
